---

num_gpus: 1 #Select number of GPUs to use
gpu_ids: 0 #IDs of GPUs to use
batch_size: 32 #Batch size
dense_flag: 0 #Use Twin-NN or Twin-DN model (0 for Twin-DN)
learning_rate: 5e-4 
weight_decay: 1e-6
epochs: 25 
log_interval: 20
save_flag: 1 #Save model to disk?
save_epoch_interval: 5 #epoch frequency for saving model
data_dir: Data/
results_dir: Results/
save_tag: TwinNN-Feb2024-5e-4/
